name: Deploy React App

on:
  push:
    branches:
      - main  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Change to the Node version you are using

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy
        run: |
          

      # Optionally, you can add steps to notify or log deployment success
